### ISSUE TITLE
Text split by lines losses spacing

### ISSUE THREAD

**Issue by dlcrista** [0xabu/pdfannots#13]
If a pdf has the following:

"This is a
sample statement"

The output that is returned is: "This is a samplestatement"

The new line information is lost.

**Comment by 0xabu** [comment]
Are you sure? The only time that should happen is when there's a hyphen:

"This is an ex-
tended line."

will turn into "This is an extended line." (which sometimes results in missing hyphens that needed to stay), but all other spaces should be preserved. See https://github.com/0xabu/pdfannots/blob/master/pdfannots.py#L129

If you have an example where it's broken, please provide a copy of the PDF if you can.

**Comment by dlcrista** [comment]
This occurs when the text is confined by a certain margin. One example is when there s a text box.


[sample.pdf](https://github.com/0xabu/pdfannots/files/2891111/sample.pdf)

**Comment by 0xabu** [comment]
Ok, I'll take a look.

**Comment by 0xabu** [comment]
Ok, the problem is that there's a space character on the first line outside the highlight which then blocks us from capturing the newline:

```
Captured text:  <LTChar 153.666,696.300,159.243,707.500 matrix=[1.00,0.00,0.00,1.00, (153.67,699.10)] font='ABCDEE+Calibri' adv=5.5775999999999994 text='e'>
Not captured text (no hit):  <LTChar 159.243,696.300,161.775,707.500 matrix=[1.00,0.00,0.00,1.00, (159.24,699.10)] font='ABCDEE+Calibri' adv=2.5312 text=' '>
Not captured anno (no hit):  <LTAnno '\n'>
Captured text:  <LTChar 89.725,681.100,94.104,692.300 matrix=[1.00,0.00,0.00,1.00, (89.72,683.90)] font='ABCDEE+Calibri' adv=4.3792 text='s'>
```
I'll need to think about how to handle this... perhaps look at the changing y coordinate and insert a newline if we didn't already see one, or capture newlines even outside the annotation region.

**Comment by dlcrista** [comment]
It looks like receive_layout recognizes that there's a newline there:
![image](https://user-images.githubusercontent.com/26131587/53203976-6893b300-35df-11e9-8acc-3e5f437ec768.png)

Interestingly, it isn't captured:
![image](https://user-images.githubusercontent.com/26131587/53204105-b0b2d580-35df-11e9-8e42-c117b3d5a117.png)

**Comment by 0xabu** [comment]
Yes, it's because we only capture the LTAnno items (which don't have coordinates of their own) when the previous item was captured, and in this case the previous item was a space character that is outside the bounds of the highlight box. I haven't seen this, perhaps it's because my PDF annotation tool doesn't draw such tight boxes. Like I said, we can probably fix it by special-casing newlines.
