### ISSUE TITLE
Redirected stdout on Windows uses a non-UTF8 encoding

### ISSUE THREAD

**Issue by 0xabu** [0xabu/pdfannots#84]
On Windows (not WSL), the following command produces a UTF8-encoded output file:
```
python3 -m pdfannots foo.pdf -o annots.txt
```

The following command does not, instead the resulting file has an 8-bit encoding -- on my machine, it uses some variant of ISO8859, but is presumably dependent on the codepage.
```
python3 -m pdfannots foo.pdf > annots.txt
```

As a workaround, when using Windows Python, it's advisable to use the -o option to write clean UTF8.

Related: #44

**Comment by 0xabu** [comment]
On second thought, I believe this is by design for Windows. We currently respect the native codepage for sys.stdout (only explicit output files are opened as UTF8), and I suspect that if we did try to overwrite the text encoding for sys.stdout, we'd see garbage when writing to the (non-redirected) console.

**Comment by Proeliorr** [comment]
Hello,

Following your solution:

Using -o option instead of redirecting (>) the output does work for me only while creating .md file and does not work during creating JSON version. 

**Anaconda prompt (Python 3.11.4) command lines:**

(German_python) >  pdfannots PDFpath -f json -o path\filename.txt

(German_python) >  pdfannots PDFpath -f md -o path\filename.txt

**Comments:**

Algorithm displays the results properly.
![powershell_yL7TcWs2uR](https://github.com/0xabu/pdfannots/assets/110690864/e52e481f-650e-4ddb-8444-f4471108f3a5)

Although, only the .md file has correct encoding or rather displays international_signs

.md file:
![Uploading notepad_LD8oG0k1cs.png…]()

while the json file (saved both as .txt or .json) does not change the result for the expected one.

![notepad++_jlfvWWnyN5](https://github.com/0xabu/pdfannots/assets/110690864/37c53f9b-64de-47d3-8d7f-33208709aef2)

**Comment by 0xabu** [comment]
Aha, ok so this is caused by https://docs.python.org/3/library/json.html#character-encodings specifically:
> As permitted, though not required, by the RFC, this module’s serializer sets ensure_ascii=True by default, thus escaping the output so that the resulting strings only contain ASCII characters.

I believe that what you're seeing is valid JSON, but I agree it would make more sense to emit utf8 there.

**Comment by 0xabu** [comment]
@Proeliorr I think with -o you should now get non-escaped utf8 in JSON output. Reopen if you still have issues.
